#!/bin/bash

# Test script for the render endpoint
# This script demonstrates how to use the API

echo "Testing Viral Quote Engine API Render Endpoint"
echo "=============================================="
echo

# Sample HTML content
HTML_CONTENT='<!DOCTYPE html>
<html>
<head>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .quote {
            text-align: center;
            font-size: 24px;
            max-width: 600px;
            padding: 20px;
            border-radius: 10px;
            background: rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div class="quote">
        <h1>🚀 Viral Quote</h1>
        <p>"The only way to do great work is to love what you do."</p>
        <small>- Steve Jobs</small>
    </div>
</body>
</html>'

# Create JSON payload
PAYLOAD=$(cat <<EOF
{
    "html": "${HTML_CONTENT}",
    "width": 800,
    "height": 600,
    "watermark": "Generated by Viral Quote Engine"
}
EOF
)

echo "Payload prepared:"
echo "- HTML length: ${#HTML_CONTENT} characters"
echo "- Dimensions: 800x600"
echo "- Watermark: Generated by Viral Quote Engine"
echo

echo "To test this endpoint with a running server, use:"
echo
echo "curl -X POST http://localhost/api/render \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '${PAYLOAD}'"
echo
echo "Expected response:"
echo '{"image_url":"http://localhost/public/renders/render_xxx_123456.png"}'
echo
echo "Note: This requires a web server running and Puppeteer/Chrome installed for browsershot."